on:
  pull_request:
  push:
    branches:
      - master

name: CI

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --all --check -- --config=imports_granularity=Crate
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack
      - run: cargo hack clippy --workspace --each-feature -- -D warnings
      - run: cargo hack test --workspace --each-feature
